get-gpg-key: use a more resilient key fetching
Ubuntu's GPG servers sometimes threw errors if presented with TLSv1.3
capable handshake messages.

Henceforth keyservers from the SKS pool will be used. This spreads
load when images are built at the same time (among pool members), decreases
the probability of a widespread failure when fetching keys (in case
Ubuntu's host is down), and due to a second connection attempt to a
then new host (it's a rotation of hosts when using the pool) individual
resiliency is increased.

diff --git a/contrib/usr/bin/get-gpg-key b/contrib/usr/bin/get-gpg-key
--- a/contrib/usr/bin/get-gpg-key
+++ b/contrib/usr/bin/get-gpg-key
@@ -1,20 +1,31 @@
 #!/bin/bash
 #
 # author:   W. Mark Kubacki <wmark@hurrikane.de>
-# revision: 2016-05-29 #1
+# revision: 2017-04-02 #2
 
 set -euo pipefail
 
 params=()
+params+=("--fail" "--silent" "--show-error")
+params+=("--connect-timeout" "2")
+
+keyquery=()
 for KEYID; do
-  if (( ${#params[@]} > 0 )); then
-    params+=("--next")
+  if (( ${#keyquery[@]} > 0 )); then
+    keyquery+=("--next")
   fi
-  params+=("--header" "Accept: text/plain")
-  params+=("-L" "https://keyserver.ubuntu.com/pks/lookup?op=get&exact=on&fingerprint=on&search=${KEYID}")
+  keyquery+=("--header" "Accept: text/plain;q=0.9,text/html;q=0.8")
+  keyquery+=("--location")
+  keyquery+=("--cacert" "/etc/ssl/certs/sks-keyservers.netCA.pem")
+  keyquery+=("https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&exact=on&fingerprint=on&search=${KEYID}")
 done
 
-if (( ${#params[@]} > 0 )); then
-  curl -fsS "${params[@]}" | \
-  sed -n '/^-----BEGIN/,/^-----END/p'
+if (( ${#keyquery[@]} > 0 )); then
+  # Allow for a second attempt, in case we got an server with an outdated OpenSSL version.
+  if ! curl "${params[@]}" "${keyquery[@]}" \
+       | sed -n '/^-----BEGIN/,/^-----END/p'; then
+    sleep 1
+    curl "${params[@]}" "${keyquery[@]}" \
+    | sed -n '/^-----BEGIN/,/^-----END/p'
+  fi
 fi
